In [1]:
import glob, re
import numpy as np
import pandas as pd
from sklearn import *
from datetime import datetime

G:\Anaconda2\envs\py36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
G:\Anaconda2\envs\py36\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
G:\Anaconda2\envs\py36\lib\site-packages\sklearn\learning_curve.py:22: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)

In [2]:
data = {
    'ar': pd.read_csv('../data/air_reserve.csv'),
    'as': pd.read_csv('../data/air_store_info.csv'),
    'hs': pd.read_csv('../data/hpg_store_info.csv'),
    'trn': pd.read_csv('../data/air_visit_data.csv'),  # with the visitors column, which is the target
    'hr': pd.read_csv('../data/hpg_reserve.csv'),
    'id': pd.read_csv('../data/store_id_relation.csv'),
    'tst': pd.read_csv('../data/sample_submission.csv'),
    'hol': pd.read_csv('../data/date_info.csv').rename(columns={'calendar_date':'visit_date'})  # advanced features
    }
print(1)

1

In [3]:
data['hr'] = pd.merge(data['hr'], data['id'], how='inner', on=['hpg_store_id'])

In [5]:
for df in ['ar','hr']:
    data[df]['visit_datetime'] = pd.to_datetime(data[df]['visit_datetime'])
    data[df]['visit_datetime'] = data[df]['visit_datetime'].dt.date
    data[df]['reserve_datetime'] = pd.to_datetime(data[df]['reserve_datetime'])
    data[df]['reserve_datetime'] = data[df]['reserve_datetime'].dt.date
    data[df]['reserve_datetime_diff'] = data[df].apply(lambda r: (r['visit_datetime'] - r['reserve_datetime']).days, axis=1)
    tmp1 = data[df].groupby(['air_store_id','visit_datetime'], as_index=False)[['reserve_datetime_diff', 'reserve_visitors']].sum().
    rename(columns={'visit_datetime':'visit_date', 'reserve_datetime_diff': 'rs1', 'reserve_visitors':'rv1'})
    tmp2 = data[df].groupby(['air_store_id','visit_datetime'], as_index=False)[['reserve_datetime_diff', 'reserve_visitors']].mean().
    rename(columns={'visit_datetime':'visit_date', 'reserve_datetime_diff': 'rs2', 'reserve_visitors':'rv2'})
    data[df] = pd.merge(tmp1, tmp2, how='inner', on=['air_store_id','visit_date'])

In [6]:
data['ar']

               air_store_id  visit_date  rs1  rv1        rs2        rv2
0      air_00a91d42b08b08d9  2016-10-31    0    2   0.000000   2.000000
1      air_00a91d42b08b08d9  2016-12-05    4    9   4.000000   9.000000
2      air_00a91d42b08b08d9  2016-12-14    6   18   6.000000  18.000000
3      air_00a91d42b08b08d9  2016-12-17    6    2   6.000000   2.000000
4      air_00a91d42b08b08d9  2016-12-20    2    4   2.000000   4.000000
5      air_00a91d42b08b08d9  2017-02-18    5    9   5.000000   9.000000
6      air_00a91d42b08b08d9  2017-02-23    2   12   2.000000  12.000000
7      air_00a91d42b08b08d9  2017-03-01   11    3  11.000000   3.000000
8      air_00a91d42b08b08d9  2017-03-14    0    4   0.000000   4.000000
9      air_00a91d42b08b08d9  2017-03-21    5    3   5.000000   3.000000
10     air_00a91d42b08b08d9  2017-03-24    1    2   1.000000   2.000000
11     air_00a91d42b08b08d9  2017-04-04    2    2   2.000000   2.000000
12     air_0164b9927d20bcc3  2016-10-28   10   12   5.000000   6.000000
13     air_0164b9927d20bcc3  2016-11-01    5   10   2.500000   5.000000
14     air_0164b9927d20bcc3  2016-11-02    0    3   0.000000   3.000000
15     air_0164b9927d20bcc3  2016-11-08    8    9   8.000000   9.000000
16     air_0164b9927d20bcc3  2016-11-10   43    6  21.500000   3.000000
17     air_0164b9927d20bcc3  2016-11-11    1    4   0.500000   2.000000
18     air_0164b9927d20bcc3  2016-11-14   22   17   7.333333   5.666667
19     air_0164b9927d20bcc3  2016-11-15    4    3   4.000000   3.000000
20     air_0164b9927d20bcc3  2016-11-16    0    2   0.000000   2.000000
21     air_0164b9927d20bcc3  2016-11-18   13   13   6.500000   6.500000
22     air_0164b9927d20bcc3  2016-11-21    6    3   6.000000   3.000000
23     air_0164b9927d20bcc3  2016-11-22   22    9  11.000000   4.500000
24     air_0164b9927d20bcc3  2016-11-24    7    2   7.000000   2.000000
25     air_0164b9927d20bcc3  2016-11-26   39   10  39.000000  10.000000
26     air_0164b9927d20bcc3  2016-11-28    1    2   1.000000   2.000000
27     air_0164b9927d20bcc3  2016-12-02    0    3   0.000000   3.000000
28     air_0164b9927d20bcc3  2016-12-05   11    4   5.500000   2.000000
29     air_0164b9927d20bcc3  2016-12-06    1    2   1.000000   2.000000
...                     ...         ...  ...  ...        ...        ...
29800  air_fea5dc9594450608  2017-03-08    5    2   5.000000   2.000000
29801  air_fea5dc9594450608  2017-03-10    3    3   3.000000   3.000000
29802  air_fea5dc9594450608  2017-03-11    3    7   1.000000   2.333333
29803  air_fea5dc9594450608  2017-03-16    2    3   2.000000   3.000000
29804  air_fea5dc9594450608  2017-03-17   30   11  10.000000   3.666667
29805  air_fea5dc9594450608  2017-03-18   49   10  24.500000   5.000000
29806  air_fea5dc9594450608  2017-03-21    0    5   0.000000   2.500000
29807  air_fea5dc9594450608  2017-03-22    1    2   1.000000   2.000000
29808  air_fea5dc9594450608  2017-03-23    0    8   0.000000   8.000000
29809  air_fea5dc9594450608  2017-03-24    0    2   0.000000   2.000000
29810  air_fea5dc9594450608  2017-03-25    2    6   0.666667   2.000000
29811  air_fea5dc9594450608  2017-03-29   18    2  18.000000   2.000000
29812  air_fea5dc9594450608  2017-03-30   15    5   7.500000   2.500000
29813  air_fea5dc9594450608  2017-04-01    0    2   0.000000   2.000000
29814  air_fea5dc9594450608  2017-04-05    6    4   6.000000   4.000000
29815  air_fea5dc9594450608  2017-04-07    1    2   1.000000   2.000000
29816  air_fea5dc9594450608  2017-04-08    6    5   6.000000   5.000000
29817  air_fea5dc9594450608  2017-04-11    0    4   0.000000   4.000000
29818  air_fea5dc9594450608  2017-04-12    1    2   1.000000   2.000000
29819  air_fea5dc9594450608  2017-04-14    1    2   1.000000   2.000000
29820  air_fea5dc9594450608  2017-04-15   10    4   5.000000   2.000000
29821  air_fea5dc9594450608  2017-04-18    6    2   6.000000   2.000000
29822  air_fea5dc9594450608  2017-04-19    0    2   0.000000   2.000000
29823  air_fea5dc9594450608  2017-04-20    3    6   3.000000   6.000000
29824  air_fea5dc9594450608  2017-04-21   29   10   9.666667   3.333333
29825  air_fea5dc9594450608  2017-04-22    0    2   0.000000   2.000000
29826  air_fea5dc9594450608  2017-04-25    9    2   9.000000   2.000000
29827  air_fea5dc9594450608  2017-04-28   29    3  29.000000   3.000000
29828  air_fea5dc9594450608  2017-05-20   34    6  34.000000   6.000000
29829  air_fee8dcf4d619598e  2017-01-09   16    5   8.000000   2.500000

[29830 rows x 6 columns]